### ISSUE TITLE
Should we not skip PRs where the only files edited had "test" in their names or path

### ISSUE THREAD

**Issue by rgarg1** [arquillian/ike-prow-plugins#131]
Writing tests for tests would be an overkill. No?

**Comment by bartoszmajsak** [comment]
I don't really understand what you mean? Do you have concrete PR to illustrate your problem? Maybe we are missing some pattern.

**Comment by bartoszmajsak** [comment]
Here you can find all the patterns https://github.com/arquillian/ike-prow-plugins/blob/ba8e72b1a0e0619af455a7f9a0e3230ab06ed0bb/pkg/assets/config/test-keeper.yaml

Feel free to enhance this file if something is missing

**Comment by rgarg1** [comment]
https://github.com/fabric8-ui/fabric8-planner/pull/2586

**Comment by rgarg1** [comment]
@bartoszmajsak So if I can edit and copy the _test-keeper.yaml_ to the root directory of my repo, that's all I need to do?

**Comment by bartoszmajsak** [comment]
It's all in the docs ;) no need to copy, just add your stuff. But how about a PR too? (so you can drop the file when we update the plugin with your changes)

**Comment by rgarg1** [comment]
Allow me to validate my changes and a PR for general consumption would follow soon here :)

**Comment by bartoszmajsak** [comment]
@rgarg1 hero \o/

**Comment by MatousJobanek** [comment]
Hi guys, the `test` directory is a bit tricky. Let me try to explain it to you.

@rgarg1 correct me if I'm wrong, your PR has failed (for the test-keeper plugin) because you have changed some test logic/additional validation file/custom assertion or anything like that, but not really a test file. Unfortunately, we are not able to build a dependency tree (which files are used by some specific test files as an additional logic), so we cannot validate the change on this level and detect that it is only test-related file. We can work only with the file names and file paths.

As for the `test` directory. We cannot expect that all files in any `**/test/**` directory contain only test-related logic and at the same time we cannot expect that all files in this type of directory are not related to the production. When we validate the files, we take the whole path from the root of the project, so with the fact that we support a bunch of programming languages, it can very easily happen that the path can contain some `test` subdirectory. Consider for example the [arquillian-core](https://github.com/arquillian/arquillian-core) project - it has a test module containing a production code.

As for the proposition to add the test directories to the exclusions - that will cause an additional problem. If a file is excluded then it means that it is removed completely from the validation process, which means that it cannot be detected as a test. In other words, if the whole directory `test` was excluded then no test in this directory would be detected and could cause more false positives in additional PRs.

Summing this up:
We cannot add the proposed directories to the list of exclusions nor inclusions. 
There are 3 possible solutions for you:
1. Use for such a cases `/ok-without-tests` command
2. You can add the whole directory to inclusions in your configuration file so will be applied only to your repository. As a side effect, all files in the directory will be considered as test files. 
3. You can try to find some pattern of file names that would include such test-related files but not any production related code and add it to your list of inclusions in your config file.

**Comment by rgarg1** [comment]
Thanks @MatousJobanek for the detailed explanation. 

I like your second suggestion, so if I include something like tests/**/*.ts, would it mean that:
- All .ts files under _tests_ dir (even inside deeply nested path) would be considered as tests
- Any changes to these files will not be flagged by the tool

?

**Comment by MatousJobanek** [comment]
> All .ts files under tests dir (even inside deeply nested path) would be considered as tests

yes

> Any changes to these files will not be flagged by the tool

every PR will be validated by the tool, but if the changed files are only test files, then it will pass. The only case when it would fail is when the PR contained only deletion (only deleted tests).

> An edit to .ts files would be considered as test added

any added line in the tests file is considered as test added. so yes, as you said :-)

**Comment by rgarg1** [comment]
@MatousJobanek 

Sample this PR: https://github.com/fabric8-ui/fabric8-planner/pull/2605

The checker is complaining about missing tests, even while the config is in place. The message from the tool provides me a link to my config file, but apparently, this link is broken. Could this be the root cause of the problem that the tool is ignoring my configuration, or the config itself is wrong?

Path to config as reported by the tool (broken): https://github.com/fabric8-ui/fabric8-planner/c64eb215f4bd0b6f61ac3390d3c817d592e7cfac/test-keeper.yml

Actual path to the config: https://github.com/fabric8-ui/fabric8-planner/blob/c64eb215f4bd0b6f61ac3390d3c817d592e7cfac/test-keeper.yml

**Comment by MatousJobanek** [comment]
@rgarg1 Sorry for my late response - I somehow missed your comment. Yeah, it seems that the link is broken, which means that the config isn't correctly loaded. I'll take a look at it today.

**Comment by rgarg1** [comment]
Thanks @MatousJobanek

**Comment by MatousJobanek** [comment]
Ok, so the config should be loaded - this is the URL the config is taken from https://raw.githubusercontent.com/fabric8-ui/fabric8-planner/c64eb215f4bd0b6f61ac3390d3c817d592e7cfac/test-keeper.yml
I just have to fix the link that is pasted into the message.

The reason why it complained about missing test is that none of the changed files matches the given patterns.
Changed files are:
`src/tests/ui/planner/workitem-quickpreview.ts`
`src/tests/specs/collaboratorTest.spec.ts`
and the test patterns:
```
  - 'test/**/*.ts'
  - 'tests/**/*.ts'
```
The patterns expects that the path should start with either `test` or `tests`, not `src`. so you would need to change the patterns to:
```
  - 'src/test/**/*.ts'
  - 'src/tests/**/*.ts'
```

**Comment by MatousJobanek** [comment]
issue for the wrong link is here: https://github.com/arquillian/ike-prow-plugins/issues/172
PR with the fix is here: https://github.com/arquillian/ike-prow-plugins/pull/173

**Comment by rgarg1** [comment]
Awesome @MatousJobanek @hemanik @dipak-pawar

**Comment by MatousJobanek** [comment]
From the discussion, it seems that all the questions have been answered and all bugs fixed so I'm closing this issue. 
If there is still anything that is not clear or fixed, feel free to reopen it or create a new one.
